export const ENV = {
  API_URL: process.env.NEXT_PUBLIC_API_URL!,
  SOCKET_URL: process.env.NEXT_PUBLIC_SOCKET_URL!,
  JWT_SECRET: process.env.JWT_SECRET!,
  GOOGLE_MAPS_API_KEY: process.env.GOOGLE_MAPS_API_KEY!,
  GOOGLE_MAPS_SECRET_KEY: process.env.GOOGLE_MAPS_SECRET_KEY!,
  MERCADO_PAGO_PUBLIC_KEY: process.env.MERCADO_PAGO_PUBLIC_KEY!,
  R2_PUBLIC_URL: process.env.NEXT_PUBLIC_R2_URL || 'https://pub-1647a59e75094933942bbd9856df1032.r2.dev',
};
